export default {
  SignUp: 'Sign up',
  Login: 'Log in',
  useName: 'User name',
  ENTER_USERNAME: 'e.g. maria93',
  email: 'Email',
  password: 'Enter Password',
  continueGoogle: 'Continue With Google',
  continueFacebook: 'Continue With Facebook',
  or: 'or',
  join: 'Join',
  Strength: 'Strength',
  veryPoor: 'Very Poor',
  PasswordGuid: 'at least 8 characters, including a number',
  passPlaceholder: 'e.g.maria93',
  emailPlaceholder: 'example@gmail.com',
  searchPixabay: 'Search Pixabay',
  passwordRequired: ' at least 8 characters, including a number',
  SignupDownload: ' Sign up to download unlimited full',
  resolutionMedia: 'resolution media',
  Continue_with_Facebook: 'Continue with Facebook',
  Continue_with_Google: 'Continue with Google',
  forget: 'forget password',
  exampleMail: 'example@gmail.com',
  paswordLabel: '* Password',
  useNamelabel: '* Username',
  emailLabel: '* Email',
  checklist: 'Checklists',
  searchChecklist: ' Search Checklists...',
  title:'Title',
  enterTitle:'Enter Title',
  description:'Description',
  enterDescription:'Enter Description....',
  status:'Status',
  save:'Save',
  draft:'Save Draft',
  userName_Required:'Name is required',
  ENTER_VALID_EMAIL:'Please enter valid email',
  EMAIL_REQUIRED:'Email is required',
  PASS_SMALL_LETTERS:'Password must have a small letter',
  PASS_CAP_LETTERS:'Password must have a capital letter',
  PASS_NUMBER:'Password must have a number',
  PASS_MIN_CHAR:'Password must be at least',
  CHARCTERS:'characters',
  PASS_REQUIRED:'Password is required',
  



};
