export default {
  DASHBOARD: 'Dashboard',
  ABOUT_US: 'aboutUs',
  CART: 'Cart',
  CART_STACK: 'Cart Stack',
  WISHLIST: 'Wishlist',
  WISHLIST_STACK: 'Wishlist Stack',
  SEARCH_SCREEN: 'Search Screen',
  HOME_SCREEN: 'Home Screen',
  HOME_STACK: 'Home Stack',
  SIGNUP_SCREEN: 'SignupScreen',
  CHECKOUT: 'CHECKOUT',
  CATEGORIES: 'Categories',
  CATEGORIES_STACK: 'Categories Stack',
  PROFILE: 'Profile',
  PROFILE_STACK: 'Profile Stack',
  PRODUCT_LIST: 'Product List',
  PRODUCT_DETAILS: 'Product Detail',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  BOTTOM_TAB: 'Bottom Tab',
};
